-- AlterTable
ALTER TABLE "Course" ALTER COLUMN "order" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "order" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "Question" ALTER COLUMN "order" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "order" SET DEFAULT 0;

-- AlterTable
ALTER TABLE "UserQuestion" ADD COLUMN IF NOT EXISTS "order" DOUBLE PRECISION NOT NULL DEFAULT 0;
